language: cpp
dist: trusty
sudo: required

compiler:
    - gcc
    
os:
    - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_script:
    - export CC=gcc-7
    - export CXX=g++-7
    - sudo apt install wget unzip
    - version="3.2.1"
    - wget "https://github.com/glfw/glfw/releases/download/${version}/glfw-${version}.zip"
    - unzip glfw-${version}.zip
    - cd glfw-${version}
    - sudo apt-get install cmake xorg-dev libglu1-mesa-dev
    - sudo cmake -G "Unix Makefiles"
    - sudo make
    - sudo make install
    - cd ..
    - sudo apt install mesa-common-dev libxinerama-dev libxcursor-dev cmake-qt-gui libglew-dev
    - sudo apt-get install xorg-dev libx11-dev libxrandr-dev libxi-dev libudev-dev libopenal-dev libdevil1c2 libdevil-dev libsfml-dev
    - cmake ./
    
script:
    - make
