os:
    - windows
    - linux

language: cpp

compiler:
    - gcc
    - clang

before_script:
    - cmake .

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make                             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make                           ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then choco install make; mingw32-make ; fi
