[Meta]
title = "level_name"
type = level

# This level can be ended by Rubeus on command. 
# Objects do not carry over.
# Use Wiki to know about advanced features such as begin, and end procedures. 

[[Objects]]
# These objects remain alive while the entire time that Rubeus is running.

[default_color_object]
name = "default_color_object"
position = [x = 3.0, y = 3.0]
size = [width = 3.0, height = 3.0]
color = [r = 255, g = 0, b = 0]

# Add all the objects' names inside TOML tables with properties as shown above. Use the Wiki for advanced features like textures and colliders.